
import React, { useState, useEffect } from 'react';
import { 
  FileText, Plus, Trash2, ChevronRight, CheckCircle2, 
  Play, AlertCircle, X, ShieldAlert, Clock, Activity, ArrowLeft, Save,
  Download, Loader2, CheckCircle, Terminal
} from 'lucide-react';
import { Severity, PlaybookStep } from '../types';

interface PlaybookEntry {
  id: string;
  title: string;
  severity: Severity;
  stepsCount: number;
  category: string;
  description: string;
  steps: PlaybookStep[];
}

const initialPlaybooks: PlaybookEntry[] = [
  { 
    id: '1', 
    title: 'Ransomware Outbreak Response', 
    severity: Severity.CRITICAL, 
    stepsCount: 4, 
    category: 'Incidents',
    description: 'Protocolo de contenção imediata para ataques de criptografia em massa.',
    steps: [
      { id: 's1', title: 'Isolate Infected Segment', description: 'Disable switch ports and isolate the affected VLAN.' },
      { id: 's2', title: 'Disable Compromised Accounts', description: 'Revoke Kerberos tokens and disable AD accounts identified in logs.' },
      { id: 's3', title: 'Identify Entry Vector', description: 'Analyze VPN and Email logs to find the initial breach point.' },
      { id: 's4', title: 'Restore from Immutable Backup', description: 'Initiate recovery process using air-gapped backups.' }
    ]
  },
  { 
    id: '2', 
    title: 'Phishing Triage & Investigation', 
    severity: Severity.HIGH, 
    stepsCount: 3, 
    category: 'Email',
    description: 'Análise de cabeçalhos e anexos maliciosos reportados por usuários.',
    steps: [
      { id: 's1', title: 'Extract Headers', description: 'Use tools to parse SPF, DKIM and DMARC results.' },
      { id: 's2', title: 'Sanitize URLs', description: 'Extract and check URLs against VirusTotal and Urlscan.io.' },
      { id: 's3', title: 'Purge Mailboxes', description: 'Run search-and-destroy for the malicious hash across the tenant.' }
    ]
  },
  { 
    id: '3', 
    title: 'Unusual SSH Login Detected', 
    severity: Severity.MEDIUM, 
    stepsCount: 2, 
    category: 'Auth',
    description: 'Investigação de acessos administrativos fora do horário comercial.',
    steps: [
      { id: 's1', title: 'Verify Source IP', description: 'Check if the IP belongs to a known VPN or a blacklisted proxy.' },
      { id: 's2', title: 'Confirm with User', description: 'Trigger MFA challenge or call the owner of the credential.' }
    ]
  },
];

export const PlaybooksView: React.FC = () => {
  const [playbooks, setPlaybooks] = useState<PlaybookEntry[]>(initialPlaybooks);
  const [selectedPlaybook, setSelectedPlaybook] = useState<PlaybookEntry | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  
  // Execution State
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionStep, setExecutionStep] = useState(-1);
  const [isExporting, setIsExporting] = useState(false);

  // Form State
  const [newTitle, setNewTitle] = useState('');
  const [newCategory, setNewCategory] = useState('General');
  const [newSeverity, setNewSeverity] = useState<Severity>(Severity.MEDIUM);
  const [newSteps, setNewSteps] = useState<PlaybookStep[]>([
    { id: '1', title: '', description: '' }
  ]);

  const handleAddStep = () => {
    setNewSteps([...newSteps, { id: Date.now().toString(), title: '', description: '' }]);
  };

  const handleUpdateStep = (id: string, field: 'title' | 'description', value: string) => {
    setNewSteps(newSteps.map(s => s.id === id ? { ...s, [field]: value } : s));
  };

  const handleRemoveStep = (id: string) => {
    if (newSteps.length > 1) {
      setNewSteps(newSteps.filter(s => s.id !== id));
    }
  };

  const handleSavePlaybook = () => {
    if (!newTitle.trim()) return;

    const playbook: PlaybookEntry = {
      id: Date.now().toString(),
      title: newTitle,
      severity: newSeverity,
      category: newCategory,
      stepsCount: newSteps.length,
      description: 'Custom security workflow generated by user.',
      steps: newSteps
    };

    setPlaybooks([playbook, ...playbooks]);
    setIsCreating(false);
    resetForm();
  };

  const resetForm = () => {
    setNewTitle('');
    setNewSteps([{ id: '1', title: '', description: '' }]);
    setNewSeverity(Severity.MEDIUM);
    setNewCategory('General');
  };

  const handleExecuteWorkflow = async () => {
    if (!selectedPlaybook) return;
    
    setIsExecuting(true);
    setExecutionStep(0);

    for (let i = 0; i < selectedPlaybook.steps.length; i++) {
      setExecutionStep(i);
      await new Promise(resolve => setTimeout(resolve, 1500)); // Simula latência de execução tática
    }
    
    setExecutionStep(selectedPlaybook.steps.length);
    await new Promise(resolve => setTimeout(resolve, 1000));
    setIsExecuting(false);
    setExecutionStep(-1);
  };

  const handleExportSOP = async () => {
    if (!selectedPlaybook) return;
    
    setIsExporting(true);
    await new Promise(resolve => setTimeout(resolve, 1500)); // Simulação de build do documento

    const content = `
THREATONE - STANDARD OPERATING PROCEDURE (SOP)
================================================
PLAYBOOK: ${selectedPlaybook.title.toUpperCase()}
CATEGORY: ${selectedPlaybook.category}
SEVERITY: ${selectedPlaybook.severity}
ID: PB-${selectedPlaybook.id}
DATE EXPORTED: ${new Date().toLocaleString()}

EXECUTIVE SUMMARY
-----------------
${selectedPlaybook.description}

TACTICAL EXECUTION STEPS
------------------------
${selectedPlaybook.steps.map((step, idx) => `
STEP ${idx + 1}: ${step.title}
DESCRIPTION: ${step.description}
------------------------------------------------`).join('\n')}

DISCLAIMER: This SOP is a confidential tactical document. 
Unauthorized distribution is prohibited.
Generated by ThreatOne Enterprise.
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SOP_${selectedPlaybook.title.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setIsExporting(false);
  };

  return (
    <div className="space-y-6 relative h-full">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Security Playbooks</h1>
          <p className="text-sm text-gray-500">Automated workflows and step-by-step incident response guides.</p>
        </div>
        <button 
          onClick={() => { setIsCreating(true); setSelectedPlaybook(null); }}
          className="flex items-center gap-2 px-4 py-2 bg-soc-primary hover:bg-soc-primary/80 text-white rounded-lg text-sm font-bold transition-all shadow-lg shadow-soc-primary/20"
        >
          <Plus size={18} /> Create New Playbook
        </button>
      </div>

      {isCreating ? (
        <div className="bg-soc-card border border-soc-primary/40 rounded-2xl overflow-hidden shadow-2xl animate-in fade-in slide-in-from-bottom-4 duration-300">
          <div className="p-6 border-b border-soc-border bg-gray-900/30 flex justify-between items-center">
            <h2 className="text-lg font-bold text-white">Configure New Tactical Playbook</h2>
            <button onClick={() => setIsCreating(false)} className="text-gray-500 hover:text-white"><X size={20} /></button>
          </div>
          
          <div className="p-8 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="md:col-span-2">
                <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Playbook Title</label>
                <input 
                  type="text" 
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. Brute Force Mitigation"
                  className="w-full bg-soc-bg border border-soc-border rounded-xl py-3 px-4 text-sm focus:outline-none focus:ring-1 focus:ring-soc-primary text-white"
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Default Severity</label>
                <select 
                  value={newSeverity}
                  onChange={(e) => setNewSeverity(e.target.value as Severity)}
                  className="w-full bg-soc-bg border border-soc-border rounded-xl py-3 px-4 text-sm text-gray-300 focus:outline-none"
                >
                  <option value={Severity.CRITICAL}>CRITICAL</option>
                  <option value={Severity.HIGH}>HIGH</option>
                  <option value={Severity.MEDIUM}>MEDIUM</option>
                  <option value={Severity.LOW}>LOW</option>
                </select>
              </div>
            </div>

            <div className="space-y-4">
              <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest border-b border-soc-border pb-2">Response Steps</h3>
              <div className="max-h-[400px] overflow-y-auto space-y-3 pr-2">
                {newSteps.map((step, index) => (
                  <div key={step.id} className="p-5 bg-soc-bg border border-soc-border rounded-2xl space-y-3 relative group animate-in slide-in-from-right-2">
                    <div className="flex items-center justify-between">
                      <span className="w-6 h-6 rounded-full bg-soc-primary/20 text-soc-primary flex items-center justify-center text-[10px] font-black">
                        {index + 1}
                      </span>
                      <button 
                        onClick={() => handleRemoveStep(step.id)}
                        className="p-1.5 text-gray-600 hover:text-soc-danger hover:bg-soc-danger/10 rounded transition-all"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                    <input 
                      type="text" 
                      value={step.title}
                      onChange={(e) => handleUpdateStep(step.id, 'title', e.target.value)}
                      placeholder="Step Title (e.g. Disable VPN Access)"
                      className="w-full bg-transparent border-b border-soc-border py-1 text-sm font-bold text-white focus:outline-none focus:border-soc-primary"
                    />
                    <textarea 
                      value={step.description}
                      onChange={(e) => handleUpdateStep(step.id, 'description', e.target.value)}
                      placeholder="Action details..."
                      className="w-full bg-transparent text-xs text-gray-400 focus:outline-none resize-none h-16"
                    ></textarea>
                  </div>
                ))}
              </div>
              
              <button 
                onClick={handleAddStep}
                className="w-full border-2 border-dashed border-soc-border py-4 rounded-2xl text-gray-500 hover:text-soc-primary hover:border-soc-primary/50 hover:bg-soc-primary/5 transition-all flex items-center justify-center gap-2 text-sm font-bold"
              >
                <Plus size={18} /> Add New Step
              </button>
            </div>
          </div>

          <div className="p-6 border-t border-soc-border bg-gray-900/30 flex justify-end gap-3">
            <button 
              onClick={() => setIsCreating(false)}
              className="px-6 py-2.5 rounded-xl text-sm font-bold text-gray-500 hover:text-gray-200 transition-colors"
            >
              Discard
            </button>
            <button 
              onClick={handleSavePlaybook}
              className="px-10 py-2.5 bg-soc-primary text-white rounded-xl text-sm font-bold shadow-lg shadow-soc-primary/20 hover:scale-[1.02] transition-all flex items-center gap-2"
            >
              <Save size={18} /> Save Playbook
            </button>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {playbooks.map((pb) => (
            <div 
              key={pb.id} 
              onClick={() => setSelectedPlaybook(pb)}
              className="bg-soc-card border border-soc-border rounded-2xl p-6 hover:border-soc-primary/50 transition-all group cursor-pointer shadow-lg hover:shadow-soc-primary/5"
            >
              <div className="flex items-center justify-between mb-5">
                <div className="p-2.5 bg-gray-900 rounded-xl group-hover:text-soc-primary transition-colors border border-soc-border">
                  <FileText size={24} />
                </div>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                  pb.severity === Severity.CRITICAL ? 'bg-red-500/10 text-red-500 border border-red-500/20' :
                  pb.severity === Severity.HIGH ? 'bg-orange-500/10 text-orange-500 border border-orange-500/20' :
                  'bg-blue-500/10 text-blue-500 border border-blue-500/20'
                }`}>
                  {pb.severity}
                </span>
              </div>
              <h3 className="font-bold text-gray-100 text-lg mb-2 leading-tight">{pb.title}</h3>
              <p className="text-xs text-gray-500 line-clamp-2 mb-4">{pb.description}</p>
              
              <div className="flex items-center justify-between text-xs text-gray-500 mt-4 pt-4 border-t border-soc-border">
                <span className="font-medium">{pb.stepsCount} Steps • {pb.category}</span>
                <div className="flex items-center gap-2 text-soc-primary font-bold opacity-0 group-hover:opacity-100 transition-all">
                  Open <ChevronRight size={14} />
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* DETAIL SIDE PANEL */}
      {selectedPlaybook && (
        <>
          <div 
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[60] transition-opacity"
            onClick={() => !isExecuting && setSelectedPlaybook(null)}
          ></div>
          <div className="fixed right-0 top-0 h-full w-full max-w-xl bg-soc-card border-l border-soc-border z-[70] shadow-2xl animate-in slide-in-from-right duration-300">
             <div className="flex flex-col h-full">
                <div className="p-6 border-b border-soc-border bg-gray-900/40 flex items-center justify-between">
                   <div className="flex items-center gap-4">
                      <div className="p-3 bg-soc-primary/10 rounded-2xl text-soc-primary border border-soc-primary/20">
                        <FileText size={28} />
                      </div>
                      <div>
                        <h2 className="text-xl font-bold text-white">{selectedPlaybook.title}</h2>
                        <p className="text-[10px] text-gray-500 font-mono tracking-widest uppercase">{selectedPlaybook.category} // PB-ID: {selectedPlaybook.id}</p>
                      </div>
                   </div>
                   {!isExecuting && (
                     <button 
                      onClick={() => setSelectedPlaybook(null)}
                      className="p-2 hover:bg-gray-800 rounded-full text-gray-500 hover:text-white transition-all"
                    >
                      <X size={24} />
                    </button>
                   )}
                </div>

                <div className="flex-1 overflow-y-auto p-8 space-y-8">
                   {isExecuting && (
                     <div className="bg-soc-primary/5 border border-soc-primary/20 rounded-2xl p-6 mb-4 animate-pulse">
                        <div className="flex items-center gap-3 text-soc-primary mb-3">
                           <Activity className="animate-spin" size={20} />
                           <span className="text-sm font-bold uppercase tracking-widest">Workflow Execution in Progress...</span>
                        </div>
                        <div className="h-1.5 bg-gray-900 rounded-full overflow-hidden">
                           <div 
                            className="h-full bg-soc-primary transition-all duration-500"
                            style={{ width: `${(executionStep / selectedPlaybook.steps.length) * 100}%` }}
                           ></div>
                        </div>
                     </div>
                   )}

                   <section className="bg-soc-bg/50 p-6 rounded-2xl border border-soc-border">
                      <div className="flex items-center justify-between mb-4">
                        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-widest">Executive Summary</h4>
                        <span className={`px-2 py-1 rounded text-[10px] font-bold ${
                          selectedPlaybook.severity === Severity.CRITICAL ? 'text-red-500 bg-red-500/10' : 'text-soc-primary bg-soc-primary/10'
                        }`}>
                          {selectedPlaybook.severity} PRIORITY
                        </span>
                      </div>
                      <p className="text-sm text-gray-300 leading-relaxed italic">
                        "{selectedPlaybook.description}"
                      </p>
                   </section>

                   <section className="space-y-4">
                      <h4 className="text-sm font-bold text-white flex items-center gap-2">
                        <Terminal size={18} className="text-soc-primary" /> Execution Flow ({selectedPlaybook.stepsCount} steps)
                      </h4>
                      
                      <div className="space-y-4 relative before:absolute before:left-[11px] before:top-2 before:bottom-2 before:w-[2px] before:bg-soc-border">
                        {selectedPlaybook.steps.map((step, idx) => {
                          const isCompleted = idx < executionStep;
                          const isCurrent = idx === executionStep;
                          
                          return (
                            <div key={step.id} className={`relative pl-8 group transition-all duration-300 ${isCompleted ? 'opacity-50' : 'opacity-100'}`}>
                              <div className={`absolute left-0 top-1 w-6 h-6 rounded-full bg-soc-card border-2 flex items-center justify-center z-10 transition-colors ${
                                isCompleted ? 'border-soc-success text-soc-success' : 
                                isCurrent ? 'border-soc-primary text-soc-primary animate-pulse' : 'border-soc-border text-gray-600'
                              }`}>
                                 {isCompleted ? <CheckCircle size={14} /> : <div className={`w-2 h-2 rounded-full ${isCurrent ? 'bg-soc-primary' : 'bg-transparent'}`}></div>}
                              </div>
                              <div className={`p-4 bg-soc-bg/40 border rounded-xl transition-all ${
                                isCurrent ? 'border-soc-primary bg-soc-primary/5' : 'border-soc-border'
                              }`}>
                                 <p className={`text-sm font-bold mb-1 ${isCurrent ? 'text-soc-primary' : 'text-white'}`}>{step.title}</p>
                                 <p className="text-xs text-gray-500">{step.description}</p>
                              </div>
                            </div>
                          );
                        })}
                        {executionStep === selectedPlaybook.steps.length && (
                          <div className="relative pl-8 animate-in zoom-in-95">
                             <div className="absolute left-0 top-1 w-6 h-6 rounded-full bg-soc-success text-white flex items-center justify-center z-10">
                                <CheckCircle2 size={14} />
                             </div>
                             <div className="p-4 bg-soc-success/10 border border-soc-success/30 rounded-xl">
                                <p className="text-sm font-bold text-soc-success">Workflow Successfully Completed</p>
                             </div>
                          </div>
                        )}
                      </div>
                   </section>
                </div>

                <div className="p-8 border-t border-soc-border bg-gray-900/30 flex gap-4">
                   <button 
                    onClick={handleExecuteWorkflow}
                    disabled={isExecuting}
                    className="flex-1 bg-soc-primary hover:bg-soc-primary/80 text-white py-3.5 rounded-2xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg shadow-soc-primary/20 disabled:opacity-50 disabled:hover:scale-100"
                   >
                     {isExecuting ? <Loader2 className="animate-spin" size={18} /> : <Play size={18} />}
                     {isExecuting ? 'Running...' : 'Execute Workflow'}
                   </button>
                   <button 
                    onClick={handleExportSOP}
                    disabled={isExporting || isExecuting}
                    className="px-6 border border-soc-border hover:bg-gray-800 text-gray-400 py-3.5 rounded-2xl font-bold transition-all flex items-center gap-2 disabled:opacity-30"
                   >
                     {isExporting ? <Loader2 className="animate-spin" size={18} /> : <Download size={18} />}
                     {isExporting ? 'Exporting...' : 'Export SOP'}
                   </button>
                </div>
             </div>
          </div>
        </>
      )}
    </div>
  );
};
