
import React, { useState } from 'react';
import { Package, ClipboardCheck, Info, ChevronRight, CheckCircle2, AlertCircle, ShieldCheck, Download, Loader2 } from 'lucide-react';

const assessmentQuestions = [
  { id: 1, text: "Do you have an active Vulnerability Management program?", category: "Maturity" },
  { id: 2, text: "Is Multi-Factor Authentication (MFA) mandatory for all staff?", category: "Access Control" },
  { id: 3, text: "Do you perform regular penetration testing by 3rd parties?", category: "Maturity" },
  { id: 4, text: "Is there a documented Incident Response plan that is tested annually?", category: "Governance" },
  { id: 5, text: "Are data backups encrypted and stored in off-site/immutable locations?", category: "Protection" },
  { id: 6, text: "Are you compliant with GDPR/LGPD or relevant local privacy laws?", category: "Compliance" },
  { id: 7, text: "Do you monitor third-party sub-processors for security risks?", category: "Governance" },
  { id: 8, text: "Is there a formal security awareness training for all employees?", category: "Culture" },
  { id: 9, text: "Do you utilize EDR/XDR solutions on all corporate endpoints?", category: "Technical" },
  { id: 10, text: "Are security patches applied within 48 hours for critical CVEs?", category: "Technical" },
];

export const SupplierAssessmentView: React.FC = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const [answers, setAnswers] = useState<Record<number, boolean>>({});
  const [isFinished, setIsFinished] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleAnswer = (val: boolean) => {
    setAnswers({ ...answers, [assessmentQuestions[currentStep].id]: val });
    if (currentStep < assessmentQuestions.length - 1) {
      setCurrentStep(currentStep + 1);
    } else {
      setIsFinished(true);
    }
  };

  const calculateScore = () => {
    const score = Object.values(answers).filter(Boolean).length * 10;
    let label = 'LOW';
    let color = 'text-red-500';
    if (score >= 80) { label = 'EXCELLENT'; color = 'text-soc-success'; }
    else if (score >= 60) { label = 'MODERATE'; color = 'text-soc-warning'; }
    
    return { score, label, color };
  };

  const result = isFinished ? calculateScore() : null;

  const handleDownloadPDF = async () => {
    if (!result) return;
    
    setIsDownloading(true);
    
    // Simula a geração do PDF
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const reportContent = `
SENTINEL CTI - SUPPLIER SECURITY ASSESSMENT REPORT
==================================================
Date: ${new Date().toLocaleString()}
Reference: SSR-${Math.random().toString(36).substring(7).toUpperCase()}

EXECUTIVE SUMMARY
-----------------
Final Score: ${result.score}%
Rating: ${result.label}
Eligibility: ${result.score >= 70 ? 'APPROVED' : 'REJECTED'}

DETAILED RESPONSES
------------------
${assessmentQuestions.map(q => {
  const ans = answers[q.id] ? '[YES]' : '[NO]';
  return `${ans} ${q.text} (${q.category})`;
}).join('\n')}

--------------------------------------------------
Generated by Sentinel CTI Enterprise System
    `;

    const blob = new Blob([reportContent], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Security_Report_Supplier_${Date.now()}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setIsDownloading(false);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center">
        <div className="w-16 h-16 bg-soc-primary/10 rounded-full flex items-center justify-center mx-auto mb-4 text-soc-primary">
          <Package size={32} />
        </div>
        <h1 className="text-3xl font-bold text-white">Supplier Security Assessment</h1>
        <p className="text-gray-500 mt-2 max-w-lg mx-auto">
          Automated due diligence to evaluate cybersecurity maturity and risk exposure of third-party vendors.
        </p>
      </div>

      {!isFinished ? (
        <div className="bg-soc-card border border-soc-border rounded-2xl overflow-hidden shadow-xl">
          <div className="h-2 bg-gray-900">
            <div 
              className="h-full bg-soc-primary transition-all duration-500" 
              style={{ width: `${((currentStep + 1) / assessmentQuestions.length) * 100}%` }}
            ></div>
          </div>
          
          <div className="p-10 space-y-8">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-soc-primary uppercase tracking-widest px-3 py-1 bg-soc-primary/10 rounded-full border border-soc-primary/20">
                {assessmentQuestions[currentStep].category}
              </span>
              <span className="text-xs font-mono text-gray-500">
                Question {currentStep + 1} of {assessmentQuestions.length}
              </span>
            </div>
            
            <h2 className="text-2xl font-semibold text-gray-100 leading-tight">
              {assessmentQuestions[currentStep].text}
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
              <button 
                onClick={() => handleAnswer(true)}
                className="group p-6 bg-soc-bg border border-soc-border rounded-xl hover:border-soc-success/50 hover:bg-soc-success/5 transition-all flex items-center justify-between"
              >
                <div className="text-left">
                  <p className="font-bold text-white group-hover:text-soc-success">Yes / Implemented</p>
                  <p className="text-xs text-gray-500 mt-1">Full compliance with the requirement.</p>
                </div>
                <CheckCircle2 size={24} className="text-gray-800 group-hover:text-soc-success transition-colors" />
              </button>

              <button 
                onClick={() => handleAnswer(false)}
                className="group p-6 bg-soc-bg border border-soc-border rounded-xl hover:border-soc-danger/50 hover:bg-soc-danger/5 transition-all flex items-center justify-between"
              >
                <div className="text-left">
                  <p className="font-bold text-white group-hover:text-soc-danger">No / Partially</p>
                  <p className="text-xs text-gray-500 mt-1">Missing or incomplete implementation.</p>
                </div>
                <AlertCircle size={24} className="text-gray-800 group-hover:text-soc-danger transition-colors" />
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-soc-card border border-soc-border rounded-2xl p-10 text-center shadow-2xl animate-in zoom-in-95">
          <div className="inline-block p-4 rounded-full bg-gray-900 border border-soc-border mb-6">
            <ShieldCheck size={48} className={result?.color} />
          </div>
          
          <h2 className="text-2xl font-bold text-white mb-2">Assessment Complete</h2>
          <p className="text-gray-500 mb-8">Generated Security Score & Maturity Rating</p>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
            <div className="bg-soc-bg p-6 rounded-2xl border border-soc-border">
              <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Final Score</p>
              <p className={`text-4xl font-bold ${result?.color}`}>{result?.score}%</p>
            </div>
            <div className="bg-soc-bg p-6 rounded-2xl border border-soc-border">
              <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Status</p>
              <p className={`text-xl font-bold ${result?.color}`}>{result?.label}</p>
            </div>
            <div className="bg-soc-bg p-6 rounded-2xl border border-soc-border">
              <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Eligibility</p>
              <p className={`text-xl font-bold ${result?.score >= 70 ? 'text-soc-success' : 'text-soc-danger'}`}>
                {result?.score >= 70 ? 'APPROVED' : 'REJECTED'}
              </p>
            </div>
          </div>

          <div className="flex gap-4 justify-center">
            <button 
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className={`px-8 py-3 bg-soc-primary text-white rounded-xl font-bold shadow-lg shadow-soc-primary/20 hover:scale-105 transition-all flex items-center gap-2 disabled:opacity-50 disabled:hover:scale-100`}
            >
              {isDownloading ? (
                <>
                  <Loader2 className="animate-spin" size={20} /> Generating...
                </>
              ) : (
                <>
                  <Download size={20} /> Download PDF Report
                </>
              )}
            </button>
            <button 
              onClick={() => { setIsFinished(false); setCurrentStep(0); setAnswers({}); }}
              className="px-8 py-3 bg-gray-800 text-gray-300 rounded-xl font-bold hover:bg-gray-700 transition-all"
            >
              Restart Audit
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
